#include <gst/gst.h>
#include "plugin/libgstcl.h"


#define PACKAGE "foo"

static gboolean
plugin_init (GstPlugin * plugin)
{
//printf(stdout, "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW");
gst_element_register (plugin, "clpush", GST_RANK_NONE, GST_TYPE_PUSH);

return TRUE;
}

GST_PLUGIN_DEFINE (
  0, 1, 
  "clpush", 
  "push to opencl",
  plugin_init,
  "0.1",
  "l",
  "g",
  "h"
)
